name: Daily Stock Screener

on:
  schedule:
    - cron: '0 10 * * *'  # 9:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas
        pip install nsetools --break-system-packages

    - name: Run Screener Script
      run: python run_daily.py

    - name: Commit results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add under200_*.csv || echo "No new file to commit"
        git commit -m "📈 Daily screener update" || echo "Nothing to commit"
        git push
